/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Auto": "自动",
    "Auto Claim": "自动领取",
    "Auto Prestige": "自动声望",
    "Auto Purchase": "自动购买",
    "Base": "基础",
    "Cancel": "取消",
    "Close": "关闭",
    "Close Skill Tree": "关闭技能树",
    "Claim Earnings": "领取收益",
    "Delete Save": "删除存档",
    "Depth": "深度",
    "Damage:": "伤害:",
    "Export Save": "导出存档",
    "Gold": "黄金",
    "Gold Upgrades": "黄金升级",
    "Import Save": "导入存档",
    "Max": "最大",
    "Max Depth": "最大深度",
    "Menu": "菜单",
    "Mined Ore": "开采的矿石",
    "More Orbs": "更多宝珠",
    "Ore Multi": "矿石乘数",
    "Ore": "矿石",
    "Prestige": "声望",
    "Points": "点数",
    "Prestige Confirmation": "声望确认",
    "Ruby": "红宝石",
    "Reset": "重置",
    "Reset Game": "重置游戏",
    "Save View": "保存视图",
    "Skill Tree": "技能树",
    "Laser": "激光",
    "Drill": "钻头",
    "Missile": "导弹",
    "Orbit": "轨道",
    "Any": "任意",
    "Total Prestige": "总声望",
    "Total Ruby": "总红宝石",
    "Total Ore": "总矿石",
    "Total Gold": "总黄金",
    "Total Damage": "总伤害",
    "Time": "时间",
    "Current": "当前",
    "Copy to Clipboard": "复制到剪贴板",
    "Common": "普通",
    "Earn Prestige": "获得声望",
    "Mining": "挖矿",
    "Offline Progress": "离线进度",
    "Orbiting Damage": "轨道伤害",
    "Ore Upgrades": "矿石升级",
    "Prestige Game": "声望游戏",
    "Purchase Settings": "购买设置",
    "Save Controls": "保存控制",
    "Target Depth": "目标深度",
    "Target Depth": "升级",
    "Upgrade Ore": "升级矿石",
    "Waiting...": "等待中...",
    "You have offline earnings!": "你有离线收益!",
    "Your ore and mine power will be reset.": "你的矿石和矿石力量将被重置。",
    "Your can spend points to expand your crew and learn skills.": "你可以消耗点数来扩大你的兵团和学习技能。",
    "Are you sure you want to delete? You will lose everything and start over.": "您确定要删除吗？你将失去一切，重新开始。",
    "Are you sure you want to reset? You will not lose your victory count.": "你确定要重置吗？你不会失去你的胜利计数。",
    "Crew": "军团",
    "Blasts stone with a laser": "使用激光轰击石头",
    "Current Run Statistics": "本轮统计",
    "Active": "激活",
    "Cumulative Statistics": "累计统计",
    "Deeper": "更深",
    "Mine": "挖矿",
    "Mined": "已开采",
    "Mined Upgrades": "挖矿升级",
    "Prestige the game and start over at the surface.": "声望游戏并重新从地面开始挖矿。",
    "Shallower": "更浅",
    "Statistics View": "统计视图",
    "Upgrade": "升级",
    "You earn 1 prestige point per terrain layer cleared.": "每清除一层地形就可以获得1点声望点。",
    "Drills straight down": "直接往下钻",
    "Fire volleys of missiles": "连续发射导弹",
    "If you prestige you will be placed back on the surface.": "如果你有声望，你会被放回到地面上。",
    "Spend your points on skills in the skill tree.": "把你的点数花在技能树上的技能上。",
    "Blocks": "块",
    "Activity": "活跃",
    "Count": "数量",
    "Ave Millis": "平均毫秒",
    "Crew Brain Debug": "兵团大脑调试",
    "Performance View": "性能视图",
    "Performance Info": "性能信息",
    "GameLoop": "游戏循环",
    "Inactive": "不活跃",
    "Tot Millis": "总毫秒",
    "CrewAI-path": "兵团AI-路径",
    "CrewAI-Total": "兵团AI-总计",
    "DynamicLighting": "动态照明",
    "FindMineTargets": "寻找采矿目标",
    "LightingReset": "照明复位",
    "LoadGrid": "加载网格",
    "MonsterBrains": "怪物大脑",
    "Path-eval": "路径计算",
    "Path-find": "路径发现",
    "PostGridLoading": "网格加载后",
    "Render-blocks": "渲染块",
    "Render-crew": "渲染兵团",
    "Render-effects": "渲染效果",
    "Render--total": "渲染总计",
    "Not Active": "未激活",
    "Depth Column Rendered": "深度列渲染",
    "Display FPS": "显示FPS",
    "Effect/Skill Rendering": "效果/技能渲染",
    "FPS Throttle": "FPS节流",
    "Wireframe Tiles": "线框瓷砖",
    "FindTargets": "发现目标",
    "GenerateTerrain": "生成地形",
    "PathFinding": "寻路",
    "Render-total": "渲染总数",
    "SaveGrid": "保存网格",
    "Version": "版本",
    "Version / Release Notes": " 版本 / 更新日志",
    "Silver Upgrades": "银升级",
    "Silver": "银",
    "Total Silver": "银总数",
    "Missile Miner": "导弹矿工",
    "Misc": "杂项",
    "Teleport to Target Row": "传送到目标行",
    "Teleport Up 100 Rows": "传送100行",
    "Laser Miner": "激光矿工",
    "Orbit Miner": "轨道矿工",
    "Drill Miner": "钻头矿工",
    "Larger Crew!": "更大的兵团！",
    "Add to your crew": "添加到你的兵团",
    "Inflicts Orbiting Damage": "造成轨道伤害",
    "More Miners!": "更多矿工!",
    "Add Miners!": "添加矿工!",
    "Damage Skills": "伤害技能",
    "Upgrades": "升级",
    "Upgrade Damage": "升级伤害",
    "Upgrade skills by spending silver.": "通过花费 银 来升级技能。",
    "Citrine": "黄水晶",
    "Citrine Upgrades": "黄水晶升级",
    "Citrine upgrades.": "黄水晶升级。",
    "Additional Gold upgrade to increase gold per block mined.": "额外的黄金升级，以增加每块开采的黄金。",
    "Additional Silver upgrade to increase silver per block mined.": "额外的银升级，以增加每块开采的银。",
    "block health column rendered": "呈现的块运行状况列",
    "brain debug option moved to the settings screen": "大脑调试选项移动到设置界面",
    "Cost to unlock ore upgrade auto-purchase increased a bunch.": "解锁矿石升级自动购买的成本增加了一堆。",
    "Crew brain changes": "船员大脑变化",
    "Crew Brain Debug View": "船员大脑调试视图",
    "Crew doesn't all start out on the same spot after prestige": "船员们在获得荣誉后并不都是从同一个地方开始的",
    "Crew focuses on going deeper when bloks are wimpy": "当冰块不够坚固时，船员们专注于深入挖掘",
    "Decreased cost of the Depth damage and Mined damage upgrades.": "降低了深度伤害和采矿伤害升级的消耗。",
    "Delay: 05:00": "延迟:凌晨5",
    "Depth Damage and Mined Damage bonus cost less, values increased.": "深度伤害和采矿伤害加成减少，数值增加。",
    "Depth damage multiplier bug on game reset.": "游戏重置时深度伤害乘数错误。",
    "Depth damage values increased x10.": "深度伤害增加x10。",
    "Doubled the value of the 'Mined Damage' bonus": "“采矿伤害”加成加倍",
    "enable/disable fps displayed on the screen": "开启/关闭屏幕显示FPS",
    "Fall speed skill": "坠落速度技能",
    "Figured out where the jittery motion when falling comes from.": "弄清楚了下落时的抖动是从哪里来的。",
    "Fix: Blocks destroyed by missiles can drop loot": "修正：被导弹摧毁的块可以掉落战利品",
    "FPS throttle (15 fps, 30 fps, etc)": "FPS节流阀（15 FPS， 30 FPS等）",
    "Gold per block more expensive": "每块黄金更贵",
    "Gold upgrade cost less, values increased.": "金币升级成本降低，价值增加。",
    "Gold upgrades are more expensive.": "金币升级更昂贵。",
    "Hopefully fixed 'cycle bug' where miner gets stuck in a loop.": "希望固定的“循环错误”，矿工陷入循环。",
    "Hopefully fixed 'pause and do nothing' bug where miners just sit there and do nothing": "希望固定“暂停和什么都不做”的bug，矿工只是坐在那里什么也不做",
    "Improvements to laser targeting logic": "改进激光瞄准逻辑",
    "Increased prestige damage bonus from 10% to 20%/prestige.": "声望伤害加成从10%增加到20%。",
    "Initial Beta Release": "初始测试版",
    "Laser should be shooting at more stuff now.": "激光现在应该瞄准更多的东西了。",
    "Laser: tinkering w/ laser targeting logic": "激光：用激光瞄准逻辑进行修补",
    "Loads of small things that I don't remember": "一大堆我不记得的小事",
    "Maybe fixed bug w/ crew getting stuck. Maybe.": "也许修复了w/ crew卡住的bug。也许吧。",
    "Mined upgrades are claimed automatically by default.": "默认情况下，自动声明挖掘的升级。",
    "Mined upgrades take 30 seconds to auto-claim": "采矿升级需要30秒自动认领",
    "Miners aren't slowed when plowing through wimpy blocks": "矿工在挖掘薄弱的区块时不会放慢速度",
    "Mining a tile reveals more tiles in the direction of mining.": "挖掘一个瓷砖会在挖掘的方向上显示更多的瓷砖。",
    "Minor improvements to character decision making.": "角色决策的小改进。",
    "Missiles fire towards targets.": "导弹向目标发射。",
    "Missiles fly a little faster": "导弹飞得快一点",
    "Missiles speed increases when fall speed is accelerated.": "当下落速度加速时，导弹速度增加。",
    "Narrower prestige popup window": "更窄的威望弹出窗口",
    "New block type: Citrine (appears at level 40).": "新的方块类型：黄水晶（在40级出现）。",
    "New mined upgrade: gold (10% chance of gold upgrade after gold is unlocked)": "新开采升级：黄金（黄金解锁后有10%的机会升级黄金）",
    "Offline earnings adjusted": "调整后的线下收益",
    "Offline earnings enabled by default": "默认启用离线收益",
    "Offline earnings included in the statistics.": "线下收入纳入统计。",
    "Offline prestige earnings changed.": "线下声望收益改变。",
    "Offline support added for: ore, ruby": "为：ore， ruby添加了离线支持",
    "On-screen debug text.": "屏幕上的调试文本。",
    "Orbit: range is larger, fixed UI bug in skill tree.": "轨道：范围更大，修复了技能树的UI错误。",
    "Path finding optimization": "寻径优化",
    "Path optimization when blocks have very low health": "方块生命值很低时的路径优化",
    "Popup window background color is darker to make things easier to read": "弹出窗口的背景颜色较深，使事情更容易阅读",
    "Prestige 'Layer Clear Countdown' is 5 minutes instead of 10": "威望“层清除倒计时”是5分钟，而不是10分钟",
    "Prestige is completely removed (for now).": "声望被完全移除（目前）。",
    "Prestige points replaced by silver block.": "威望点被银块取代。",
    "Rare Block Upgrades": "稀有方块升级",
    "Re-implemented how offline earnings are calculated": "重新实现了线下收入的计算方式",
    "Rebalanced all skill damage upgrades and remaining gold upgrades.": "重新平衡了所有技能伤害升级和剩余的金币升级。",
    "Reduced rate at which block health increases per depth.": "降低了方块生命值每深度增加的速率。",
    "Reordered some things in the statistics popup.": "重新排序一些东西在统计弹出。",
    "Reworked crew search area logic": "重制船员搜索区域逻辑",
    "Reworked gold upgrades, removed OP damage upgrades.": "重制金币升级，移除OP伤害升级。",
    "Ruby Upgrades": "Ruby升级",
    "Silver damage bonus based on number of silver blocks mined instead of silver value.": "银伤害加成基于开采的银块数量，而不是银的价值。",
    "Silver damage multiplier based off of total silver instad of silver blocks mined - so that offline progress counts.": "银伤害乘数基于总银，而不是银块开采-所以离线进度计数。",
    "Simplified auto prestige": "简化汽车声望",
    "skills/effects rendered": "技能/效果呈现",
    "Slightly improved wireframe rendering mode": "略微改进线框渲染模式",
    "Slightly increased mined ore earnings.": "矿石收益略有增加。",
    "Slower auto-purchase of ore upgrades (3 minutes by default instead of 1)": "更慢的自动购买矿石升级（默认3分钟而不是1分钟）",
    "Stopped saving grids during fast falling that will never be loaded again": "停止在快速下降期间保存网格，这些网格将永远不会再次加载",
    "Terrain save optimization": "地形保存优化",
    "Tinkering with the laser to get it to fire more": "修补激光，让它发射更多",
    "Total Citrine": "总黄水晶",
    "Unlocking 1st extra miner costs 1 prestige point instead of 2.": "解锁第一个额外矿工需要消耗1点声望点，而不是2点。",
    "Version / Release Notes view (this popup)": "版本/发行说明视图（此弹出窗口）",
    "wireframe mode (render blocks as rectangles to lower GPU usage)": "线框模式（将块渲染为矩形以降低GPU使用）",
    "Yay": "耶",
    "Added a bunch of gold upgrades including gold per block.": "增加了一堆金币升级，包括每块金币。",
    "Added a time icon.": "增加了一个时间图标。",
    "Added block damage skill (too OP?)": "增加了格挡伤害技能（太OP了？）",
    "Added ruby upgrades": "添加了ruby升级",
    "Added Ruby upgrades.": "增加了Ruby的升级。",
    "Added some icons": "添加了一些图标",
    "Fixed another looping/stuck miner bug.": "修正了另一个循环/卡住的矿工错误。",
    "Fixed issue where deepest layer was not appearing in the layer progress view.": "修复了最深的图层没有出现在图层进度视图中的问题。",
    "Fixed max speed of auto purchase/claim skills": "固定的最大速度自动购买/索赔技能",
    "Fixed null pointer bug reported by player": "修正了玩家报告的空指针错误",
    "Fixed offline earnings crash bug": "修复了离线盈利崩溃的bug",
    "Fixed orbit sprite rendering issue.": "固定轨道精灵渲染问题。",
    "Fixed prestige timer reset on save load": "固定威望计时器重置保存负载",
    "Fixed skill activation/cool-down bug.": "固定技能激活/冷却错误。",
    "Fixed skill duration bug": "修复技能持续时间错误",
    "Fixed sprite for Defective Cobalt layer.": "固定精灵缺陷钴层。",
    "Removed fall speed skill, removed prestige damage upgrades.": "移除掉落速度技能，移除声望伤害升级。",
    "Removed prestige and fall mechanic.": "移除声望和掉落机制。",
    "Removed purchase limit of gold upgrades.": "移除金币升级的购买限制。",
    "Removed terrible skill tree UI, replaced with simpler button UI.": "移除糟糕的技能树UI，取而代之的是更简单的按钮UI。",
    "A damage multiplier driven by the total number of blocks mined.": "由开采的区块总数驱动的伤害乘数。",
    "A damage multiplier driven by the total number of earned rubies.": "伤害乘数由赚取的红宝石总数驱动。",
    "Auto Purchase: The game will very slowly purchase ore upgrades on your behalf.": "自动购买：游戏将非常缓慢地为你购买矿石升级。",
    "Auto Purchase: You can spend silver to unlock the auto purchase feature. This will very slowly purchase ore upgrades on your behalf.": "自动购买：你可以用银来解锁自动购买功能。这将非常缓慢地购买矿石升级代表你。",
    "Citrine blocks start appearing at level 40. Citrine apply an automatic damage bonus.": "黄水晶方块在40级开始出现。黄水晶有自动伤害加成。",
    "Citrine Damage +500: Adds to a damage multiplier applied against the total citrine.": "黄水晶伤害+500：增加对总黄水晶的伤害乘数。",
    "Damage / Silver: A damage multiplier driven by the total silver earned by the crew.": "伤害/银：乘员获得的总银驱动的伤害乘数。",
    "Damage Upgrades": "损害升级",
    "Depth Damage: A damage multiplier affected by the max depth of the crew.": "深度伤害：乘员最大深度影响伤害乘数。",
    "Gold blocks start appearing at level 10.": "金币块从10级开始出现。",
    "Gold Damage: Upgrades the Gold damage multiplier.": "金币伤害：升级金币伤害乘数。",
    "Gold: +1/block: Affects how much gold is earned per gold block mined.": "金币：+1/块：影响每挖一块金币赚多少金币。",
    "Gold: +10/block: Affects how much gold is earned per gold block mined.": "金币：+10/块：影响每挖一块金币赚多少金币。",
    "Gold: +250/block: Adds to the amount of gold earned per gold block mined.": "金币：+250/块：增加每开采一块金币所赚取的金币数量。",
    "Gold: +50/block: Adds to the amount of gold earned per gold block mined.": "金币：+50/块：每开采一块金币，增加获得的金币数量。",
    "Information": "信息",
    "Mined Damage: The damage value added to the damage multiplier of the mined upgrades. This affects the 'Mined' value.": "采矿伤害：增加到采矿升级的伤害乘数的伤害值。这会影响“已挖掘”值。",
    "Misc Upgrades": "其他升级",
    "Offline: Adds to the amount of time the game will give you credit for being offline. Earn ore and gold and other currencies with the game off.": "离线：增加游戏给予你离线积分的时间。在游戏关闭的情况下赚取矿石、黄金和其他货币。",
    "Ore Bonus: +2000: Adds to the multiplier that is applied to the amount of ore earned from an ore block.": "矿石加成：+2000：加到从矿石块中获得的矿石数量的乘数上。",
    "Ore Bonus: +250: Adds to the multiplier that is applied to the amount of ore earned from an ore block.": "矿石加成：+250：加到从矿石块中获得的矿石数量的乘数上。",
    "Ore Bonus: Adds to the multiplier that is applied to the amount of ore earned from an ore block.": "矿石奖励：加到从矿石块中获得的矿石数量的乘数上。",
    "Ruby blocks start appearing at level 20. Rubies apply an automatic damage bonus.": "20级开始出现红宝石方块。红宝石具有自动伤害加成。",
    "Ruby: +1/block: Adds to the amount of ruby earned per ruby block mined.": "红宝石：+1/块：增加每开采一个红宝石块所获得的红宝石数量。",
    "Silver blocks earn you a silver currency, which can be used to purchase various upgrades.": "银块可以让你获得银货币，可以用来购买各种升级。",
    "Silver damage multiplier based off of total silver instead of silver blocks mined - so that offline progress counts.": "银伤害乘数基于总银而不是开采的银块-所以离线进度计数。",
    "Silver: +1/block: Adds to the amount of silver earned per silver block mined.": "银：+1/块：增加每开采一个银块所获得的银量。",
    "Silver: +10/block: Adds to the amount of silver earned per silver block mined.": "银：+10/块：增加每开采一个银块所获得的银数量。",
    "Silver: +150/block: Adds to the amount of silver earned per silver block mined.": "银：+150/块：增加每开采一个银块获得的银量。",
    "Silver: +500/block: Adds to the amount of silver earned per silver block mined.": "银：+500/块：增加每开采一个银块获得的银数量。",
    "Some upgrade blocks will give you gold. This only starts happening when your crew has reached the requried depth.": "一些升级方块会给你金币。只有当你的船员到达所需的深度时，这种情况才会发生。",
    "Some upgrade blocks will provide a damage bonus multiplier. These blocks are represented by the 'Mined' damage value.": "一些升级方块会提供伤害加成。这些方块由“开采”伤害值表示。",
    "The Drill Miner automatically mines the tiles below his feet.": "钻矿者自动在他脚下的瓷砖上采矿。",
    "The Laser Miner shoots a laser at the nearby blocks.": "激光矿工向附近的方块发射激光。",
    "The miners all have a skill that will be active for while, and then will be disabled as it cools down.": "矿工们都有一个技能，将会激活一段时间，然后将被禁用，因为它冷却下来。",
    "The miners will occasionally mine upgrade blocks. These blocks give various bonuses.": "矿工们偶尔会开采升级区块。这些方块提供各种奖励。",
    "The Missile Miner shoots bursts of missiles at nearby blocks.": "导弹矿工向附近的方块发射导弹。",
    "The most common type of bonus is the Ore Bonus. This is just some ore that is added to your total ore amount.": "最常见的奖励类型是矿石奖励。这只是加到你的矿石总量中的一些矿石。",
    "The Orbit Miner has a number of orbs that rotate around him and damage blocks.": "轨道矿工有许多球，在他周围旋转并伤害方块。",
    "These upgrades add a damage/second value to your base damage.": "这些升级为你的基础伤害增加了一个伤害/秒值。",
    "These upgrades add to the 'Ore Multi' damage multiplier.": "这些升级增加了“矿石多重”伤害乘数。",
    "You build your mining crew by spending silver.": "你通过消耗银来组建你的采矿队伍。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Ore: +": "矿石: +",
    "Skill: ": "技能: ",
    "Type: ": "类型: ",
    "Tile Range +": "瓷砖范围 +",
    "Prestige points earned: ": "获得的声望点数: ",
    "Base: +": "基础: +",
    "Ore: x": "矿石: x",
    "Mine: x": "挖矿: x",
    "Multiplier: +": "乘数: +",
    "Bonus: +": "加成: +",
    "Current Delay: ": "当前延迟: ",
    "Damage / Max Depth: ": "伤害 / 最大深度: ",
    "Damage / Prestige: ": "伤害 / 声望: ",
    "Depth Damage +": "深度伤害 +",
    "Prestige Damage +": "声望伤害 +",
    "Ruby Damage +": "红宝石伤害 +",
    "Mined Damage +": "挖矿伤害 +",
    "Base Damage: x": "基础伤害: x",
    "Depth Damage: x": "深度伤害: x",
    "Block Damage: x": "地块伤害: x",
    "Ruby Damage: x": "红宝石伤害: x",
    "Mined Damage: x": "挖矿伤害: x",
    "Prestige Damage: x": "声望伤害: x",
    "Ore Multi: x": "矿石乘数: x",
    "Prestige +": "声望 +",
    "Bonus: x": "加成: x",
    "Ore x": "矿石 x",
    "Dirt ": "泥土 ",
    "Missiles + ": "导弹 + ",
    "Blue Green Clay": "蓝绿粘土",
    "Red Clay": "红黏土",
    "Grey Sandstone": "绿砂岩",
    "Offline time: ": "离线时间: ",
    "Prestige earned: ": "获得的声望: ",
    "Ruby earned: ": "获得的红宝石: ",
    "Ore earned: ": "获得的矿石: ",
    "Gold earned: ": "获得的黄金: ",
    "Brown Sandstone": "褐色砂岩",
    "Green Pyronxenite": "绿色辉硅矿",
    "Blue Dunite": "蓝色暗岩",
    "Deficient Hematite": "贫赤铁矿",
    "Blue Sandstone": "蓝色砂岩",
    "Layer Clear Countdown: ": "图层清除倒计时：",
    "Bloodstone": "血石",
    "Grey Orange Granite": "灰橙花岗岩",
    "Aqua Carnelion": "水色玉髓",
    "Purple Grey Quartz": "紫灰石英",
    "Red Magnetite": "红磁铁矿",
    "Rose Stone": "玫瑰石",
    "Purple Grey Granite": "紫灰花岗岩",
    "Damage / Block: ": "伤害 / 块: ",
    "Damage / Ruby: ": "伤害 / 红宝石: ",
    "Fall Speed ": "下降的速度 ",
    "FallSpeed: ": "下降的速度: ",
    "Green Slate": "绿色板岩",
    "Mined Blocks ": "开采块 ",
    "Ruby +": "红宝石 +",
    "Blue Schist": "蓝片岩",
    "Rotten Vanadium": "腐烂的钒",
    "Green Quartz": "绿石英",
    "Green Jasper": "绿色碧玉",
    "Slimy Pyrrhotite": "粘稠的磁黄铁矿",
    "Blood Agate": "血玛瑙",
    "Compressed Bauxite": "压缩铝土矿",
    "Dark Phrenite": "暗辉灰岩",
    "Blue Stone": "蓝石",
    "Defective Cobalt": "残次钴",
    "Orange Alexandrite": "橙紫翠玉",
    "Pale Blue Stone": "淡蓝色石头",
    "Green Schist": "绿片岩",
    "Red Pyronxenite": "红色辉石岩",
    "Teal Clay": "青绿色粘土",
    "Arkose Sandstone": "长石砂岩",
    "Substandard Gypsum": "劣质石膏",
    "Silver earned: ": "获得的银: ",
    "Settings screen: ": "设置屏幕: ",
    "Time: ": "时间: ",
    "Damage / Silver ": "伤害 / 银 ",
    "Damage / Block ": "伤害 / 块 ",
    "Damage: ": "伤害: ",
    "Ore +": "矿石 +",
    "Citrine earned: ": "获得的黄水晶: ",
    "Damage / Ruby ": "伤害 / 红宝石 ",
    "Delay: ": "延迟: ",
    "Blue Green Agate": "蓝绿玛瑙",
    "Auto Purchase Delay ": "自动购买延迟 ",
    "Calamitous Calcite": "灾变方解石",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/s": "/秒",
    "/Sec": "/秒",
    "/sec": "/秒",
    " (Dev tool)": " (开发者工具)",
    " / second)": " / 秒)",
    "/citrine": "/黄水晶",
    "The damage value added to the damage multiplier of the mined upgrades. This affects the 'Mined' value.": "伤害值增加到采矿升级的伤害倍数。这会影响“采矿”值。",
    "A damage multiplier affected by the max depth of the crew.": "受兵团最大深度影响的伤害乘数。",
    "Adds to a damage multiplier affected by the max depth of the crew. This affects the 'Depth' value.": "增加受兵团最大深度影响的伤害乘数。这将影响“深度”值。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)E([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    // /^Removed(.+)$/,
    // /^Fixed(.+)$/,
    // /^Added(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)\+([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Offline (.+) min$/, '离线 $1 分钟'],
    [/^Delay (.+) min$/, '延迟 $1 分钟'],
    [/^Delay (.+) sec$/, '延迟 $1 秒'],
    [/^Cool Down (.+) sec$/, '冷却 $1 秒'],
    [/^Duration (.+) sec$/, '持续 $1 秒'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.]+)E([\d\.,]+) Gold$/, '$1e$2 黄金'],
    [/^([\d\.]+)E([\d\.,]+) Ore$/, '$1e$2 矿石'],
    [/^([\d\.]+)E([\d\.,]+) Silver$/, '$1e$2 银'],
    [/^([\d\.,]+) Silver$/, '$1 银'],
    [/^([\d\.,]+) seconds$/, '$1 秒'],
    [/^([\d\.,]+) Prestige$/, '$1 声望'],
    [/^([\d\.,]+) Citrine$/, '$1 黄水晶'],
    [/^([\d\.,]+) Ruby$/, '$1 红宝石'],
    [/^([\d\.,]+) Ore$/, '$1 矿石'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Gold$/, '$1 黄金'],
    [/^\+([\d\.,]+)\/([\d\.,]+) Tile$/, '\+$1\/$2 瓷砖'],
    [/^\+([\d\.,]+) Orb$/, '\+$1 宝珠'],
    [/^\+([\d\.,]+) Tile$/, '\+$1 瓷砖'],
    [/^\+([\d\.,]+) Drill Miner$/, '\+$1 钻头矿工'],
    [/^\+([\d\.,]+) Laser Miner$/, '\+$1 激光矿工'],
    [/^\+([\d\.,]+) Orbit Miner$/, '\+$1 轨道矿工'],
    [/^\+([\d\.,]+) Missile Miner$/, '\+$1 导弹矿工'],
    [/^Range: ([\d\.,]+) Tiles$/, '范围: $1 瓷砖'],
    [/^Missiles: ([\d\.,]+)$/, '导弹: $1'],
    [/^Update ([\d\.,]+)$/, '更新 $1'],
    [/^Gold Damage \+([\d\.,]+)$/, '黄金伤害 +$1'],
    [/^Silver \+([\d\.,]+)\/block$/, '银 +$1/块'],
    [/^Silver: \+([\d\.,]+)\/block$/, '银: +$1/块'],
    [/^Ruby: \+([\d\.,]+)\/block$/, '红宝石: +$1/块'],
    [/^Ore Bonus: \+([\d\.,]+)$/, '矿石加成: +$1'],
    [/^Mined Damage: \+([\d\.,]+)$/, '采矿伤害: +$1'],
    [/^Depth Damage: \+([\d\.,]+)$/, '深度伤害: +$1'],
    [/^Gold: \+([\d\.,]+)$/, '黄金: +$1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级: $1 \/ $2'],
    [/^Depth: ([\d\.,]+) \/ ([\d\.,]+)$/, '深度: $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Gold: \+(.+)\/block$/, '黄金: +$1/块'],
    [/^\+(.+)\/block$/, '+$1/块'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);